name: Build and Release Python Package

on:
  push:
    tags:
      - 'v*'

jobs:
  build_wheel:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.13

      - name: Install dependencies
        run: python -m pip install --upgrade build

      - name: Build wheel
        run: python -m build

      - name: Upload Wheel as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: wheel-package
          path: dist/*.whl

  release:
    needs: build_wheel
    runs-on: ubuntu-latest
    steps:
      - name: Download built wheel
        uses: actions/download-artifact@v3
        with:
          name: wheel-package
          path: dist

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*.whl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}